[
    {
        id: 0,
        name: 'Original_Cola',
        stock: 4,
        price: 1000,
        buy: 0,
        obtain: 0,
        src: 'images/Original_Cola.svg',
    },
    {
        id: 1,
        name: 'Violet_Cola',
        stock: 4,
        price: 1000,
        buy: 0,
        obtain: 0,
        src: 'images/Violet_Cola.svg',
    },
    {
        id: 2,
        name: 'Yellow_Cola',
        stock: 5,
        price: 1000,
        buy: 0,
        obtain: 0,
        src: 'images/Yellow_Cola.svg',
    },
    {
        id: 3,
        name: 'Cool_Cola',
        stock: 3,
        price: 1000,
        buy: 0,
        obtain: 0,
        src: 'images/Cool_Cola.svg',
    },
    {
        id: 4,
        name: 'Green_Cola',
        stockr: 5,
        price: 1000,
        buy: 0,
        obtain: 0,
        src: 'images/Green_Cola.svg',
    },
    {
        id: 5,
        name: 'Orange_Cola',
        stock: 4,
        price: 1000,
        buy: 0,
        obtain: 0,
        src: 'images/Orange_Cola.svg',
    },
];
